
# sudo docker compose --file=./docker-compose-dev.yml up --force-recreate --build

version: '3.8'
services:

  postgresql:
    build:
      context: .
      dockerfile: ./postgresql/Dockerfile
    restart: "no"
    network_mode: "host" # 5432
    command: postgres -c shared_preload_libraries=pgaudit # pg_cron,pgsodium,pgaudit
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:?error} # postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error} # postgres
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - ./volumes/postgresql/data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest
    network_mode: "host" # 5433
    environment:
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:?error} # public
      PGRST_DB_EXTRA_SEARCH_PATH: ${PGRST_DB_EXTRA_SEARCH_PATH:?error} # public,extensions
      PGRST_DB_URI: postgres://${POSTGRES_USER:?error}:${POSTGRES_PASSWORD:?error}@0.0.0.0:5432/postgres
      PGRST_SERVER_PORT: 5433
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET:?error} # crestfall
      PGRST_JWT_SECRET_IS_BASE64: ${PGRST_JWT_SECRET_IS_BASE64:?error} # true
      PGRST_JWT_AUD: crestfall
    depends_on:
      - postgresql

  auth:
    build:
      context: ../ # path of parent directory
      dockerfile: ./auth/Dockerfile # path relative to context
    restart: "no"
    network_mode: "host" # 9090
    command: node ./index.mjs
    depends_on:
      - postgrest

  caddy:
    image: caddy:2
    network_mode: "host" # 80, 443, 443/udp
    volumes:
      - ./volumes/caddy/data:/data
      - ./volumes/caddy/config:/config
      - ./volumes/caddy/logs:/var/log/caddy/
      - ./caddy/Caddyfile-dev.cdf:/etc/caddy/Caddyfile